import localFont from 'next/font/local';
import { ReactNode } from 'react';

import { Layout } from '@/app/_layout/Layout';
import { ThemeProvider } from '@/providers';

import type { Metadata } from 'next';

import '@workspace/ui/globals.css';

const pixelMplus = localFont({
  src: '../fonts/PixelMplus10-Regular.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function fetchGitHubGraphQL<T>(query: string, variables: Record<string, any> = {}): Promise<T> {
  const GITHUB_GRAPHQL_API = 'https://api.github.com/graphql';
  const TOKEN = process.env.GIITHUB_PERSONAL_TOKEN;

  const response = await fetch(GITHUB_GRAPHQL_API, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({ query, variables }),
  });

  const json = await response.json();
  if (json.errors) {
    console.error('GitHub GraphQL API Error:', json.errors);
    throw new Error('Failed to fetch GitHub GraphQL API');
  }

  return json.data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {

  const data = await fetchGitHubGraphQL(
    `query($username:String!) {
      user(login: $username) {
        contributionsCollection {
          contributionCalendar {
            totalContributions
            weeks {
              contributionDays {
                color
                contributionCount
                date
              }
            }
          }
        }
      }
    }`, {
      username: 'daisuke-tanabe'
    });

  const result = data.user.contributionsCollection.contributionCalendar.weeks.map(({ contributionDays }) => contributionDays);


  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>

      <body className={`${pixelMplus.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Layout data={result}>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
