import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { ThemeProvider } from '@/providers';

import '@/styles/globals.css';
import localFont from 'next/font/local';
import { Layout } from '@/app/_layout/Layout';

const pixelMplus = localFont({
  src: '../fonts/PixelMplus10-Regular.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>

      <body className={`${pixelMplus.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
